import type { EntityRecord, RepositoryModule } from '../repositories';

export type BackupDiagnostic={encoding:string;rootType:'object'|'array'|'string'|'other';topLevelKeys:string[];version:string;metadataKeys:string[];metadataPath?:string;databaseRoot?:string;modulesFound:string[];moduleCounts?:Record<string,number>;encrypted:boolean;serialized:boolean;format:'master'|'legacy'|'legacy-zip'|'unknown'};
export type AdapterDisposition={module:string;index:number;reason:string};
export type LegacyAdaptation={modules:Partial<Record<RepositoryModule,unknown[]>>;diagnostic:BackupDiagnostic;quarantine:AdapterDisposition[];ignored:AdapterDisposition[]};
const aliases:Record<RepositoryModule,string[]>={
  companies:['companies','empresas','erp_3a_companies'],categories:['categories','categorias','erp_3a_categories'],clients:['clients','clientes','erp_3a_clients'],assets:['assets','bens','patrimonio','erp_3a_assets'],properties:['properties','imoveis','erp_3a_properties'],vehicles:['vehicles','veiculos','frota','erp_3a_vehicles'],bank_accounts:['bank_accounts','bancos','contas_bancarias','erp_3a_bank_accounts'],bank_movements:['bank_movements','movimentacoes_bancarias','erp_3a_bank_movements'],transactions:['transactions','historico_financeiro','financeiro','fluxo_caixa','lancamentos','erp_3a_transactions'],charges:['charges','cobrancas','agenda_cobrancas','erp_3a_charges'],recurring_series:['recurring_series','series_recorrentes','erp_3a_recurring_series'],fixed_costs:['fixed_costs','custos_fixos','custo_fixo','erp_3a_fixed_costs'],investments:['investments','investimentos','erp_3a_investments'],alerts:['alerts','alertas','erp_3a_alerts'],deletion_logs:['deletion_logs','log_exclusoes','erp_3a_deletion_logs'],receipts:['receipts','recibos','erp_3a_receipts'],company_metrics:['company_metrics','3a_rastrear','rastrear','rastreadores','equipamentos','erp_3a_company_metrics']
};
const fieldAliases:Record<string,string>={companyId:'company_id',empresaId:'company_id',categoryId:'category_id',categoriaId:'category_id',clientId:'client_id',clienteId:'client_id',assetId:'asset_id',bemId:'asset_id',bankAccountId:'bank_account_id',contaBancariaId:'bank_account_id',id_conta:'bank_account_id',chargeId:'charge_id',cobrancaId:'charge_id',seriesId:'series_id',serieId:'series_id',transactionId:'transaction_id',lancamentoId:'transaction_id',dueDate:'due_date',vencimento:'due_date',competencyDate:'competency_date',dataCompetencia:'competency_date',paidAt:'paid_at',dataPagamento:'paid_at',createdAt:'created_at',criadoEm:'created_at',updatedAt:'updated_at',atualizadoEm:'updated_at',transactionDate:'transaction_date',data:'transaction_date',date:'transaction_date',initialBalance:'initial_balance',saldoInicial:'initial_balance',initialBalanceDate:'initial_balance_date',dataSaldoInicial:'initial_balance_date',bankName:'bank_name',nomeBanco:'bank_name',accountName:'account_name',nomeConta:'account_name',accountType:'account_type',tipoConta:'account_type',movementType:'movement_type',tipoMovimento:'movement_type',movementDate:'movement_date',dataMovimento:'movement_date',customIntervalDays:'custom_interval_days',intervaloPersonalizadoDias:'custom_interval_days',startDate:'start_date',dataInicio:'start_date',endDate:'end_date',dataFim:'end_date',nextDueDate:'next_due_date',proximoVencimento:'next_due_date',currentTransactionId:'current_transaction_id',investmentDate:'investment_date',dataInvestimento:'investment_date',assetType:'asset_type',tipoBem:'asset_type',purchaseValue:'purchase_value',valorCompra:'purchase_value',purchase_value:'purchase_value',valor_patrimonial:'purchase_value',currentValue:'current_value',valorAtual:'current_value',valor_atual:'current_value',data_aquisicao:'acquisition_date',displayName:'display_name',nomeExibicao:'display_name',metricKey:'metric_key',chaveMetrica:'metric_key',measuredAt:'measured_at',medidoEm:'measured_at',nome:'name',descricao:'description',valor:'value',tipo:'type',frequencia:'frequency',endereco:'address',placa:'plate',modelo:'model',slug:'kind',cpf:'document',cnh:'cnh_number',cnh_validade:'cnh_expiry',next_increase_date:'annual_adjustment_date'};
const isObject=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value);
const findContainer=(root:Record<string,unknown>)=>[root.modules,root.tables,root.data,root.backup,root].find(isObject)as Record<string,unknown>;
const findModule=(container:Record<string,unknown>,names:string[])=>{for(const name of names){if(Array.isArray(container[name]))return{name,records:container[name]as unknown[]};}return null;};
const companyKind=(record:Record<string,unknown>)=>{const source=String(record.kind??record.type??record.name??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(/loc[\s_-]*mottus|mottus/.test(source))return'loc_mottus';if(/rastrear|rastreamento/.test(source))return'rastrear';if(/imoveis|imovel/.test(source))return'imoveis';if(/holding|grupo[\s_-]*3a/.test(source))return'holding';return record.kind;};
const normalizedWord=(value:unknown)=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
const financialType=(value:unknown)=>{const word=normalizedWord(value);if(['receita','entrada','credito','credit','in'].includes(word))return'receita';if(['despesa','saida','debito','debit','out'].includes(word))return'despesa';return value;};
const financialStatus=(value:unknown)=>{const word=normalizedWord(value);if(['pago','recebido','paid','confirmed'].includes(word))return'pago';if(['pendente','pending','aberto'].includes(word))return'pendente';if(['atrasado','overdue','vencido'].includes(word))return'atrasado';if(['cancelado','cancelled','canceled'].includes(word))return'cancelado';return value;};
const normalizeRecord=(record:unknown,module:RepositoryModule)=>{if(!isObject(record))return record;const normalized=Object.fromEntries(Object.entries(record).map(([key,value])=>[fieldAliases[key]||key,value]));if(module==='companies')normalized.kind=companyKind(normalized);if(module==='categories'||module==='transactions')normalized.type=financialType(normalized.type);if(module==='transactions')normalized.status=financialStatus(normalized.status);if(module==='properties'){normalized.tenant_client_id=record.tenant_id;normalized.rent_value=record.value;}if(module==='vehicles')normalized.tenant_client_id=record.client_id;return normalized;};

export function adaptLegacyBackup(root:unknown,base:Omit<BackupDiagnostic,'modulesFound'|'format'>):LegacyAdaptation{
  if(!isObject(root))throw new Error(root===null?'Arquivo vazio.':'Módulo incompatível: a raiz do backup antigo deve ser um objeto.');
  const container=findContainer(root),modules:LegacyAdaptation['modules']={},found:string[]=[],quarantine:LegacyAdaptation['quarantine']=[],ignored:LegacyAdaptation['ignored']=[];
  for(const[module,names]of Object.entries(aliases)as[RepositoryModule,string[]][]){const located=findModule(container,names);if(!located)continue;found.push(located.name);modules[module]=located.records.map((record,index)=>{if(!isObject(record)){quarantine.push({module,index,reason:'Registro não é um objeto.'});return record;}return normalizeRecord(record,module);});}
  const categoryAliases=new Map<string,string>(),categoryKeys=new Map<string,string>();
  modules.categories=(modules.categories||[]).filter((record,index)=>{if(!isObject(record)||typeof record.id!=='string')return true;const key=`${String(record.company_id||'')}|${String(record.name||'').trim().toLocaleLowerCase('pt-BR')}`,canonical=categoryKeys.get(key);if(!canonical){categoryKeys.set(key,record.id);return true;}categoryAliases.set(record.id,canonical);ignored.push({module:'categories',index,reason:'Categoria duplicada; referências preservadas na categoria canônica.'});return false;});
  if(categoryAliases.size)for(const records of Object.values(modules))for(const record of records||[])if(isObject(record)&&typeof record.category_id==='string'&&categoryAliases.has(record.category_id))record.category_id=categoryAliases.get(record.category_id)!;
  const assetKeys=new Set<string>();modules.assets=(modules.assets||[]).filter((record,index)=>{if(!isObject(record)||!record.code)return true;const key=`${String(record.company_id||'')}|${String(record.code).trim().toLocaleLowerCase('pt-BR')}`;if(!assetKeys.has(key)){assetKeys.add(key);return true;}quarantine.push({module:'assets',index,reason:'Código de bem duplicado na mesma empresa; registro e dependências enviados para quarentena.'});return false;});
  const plates=new Set<string>(),duplicateVehicleIds=new Set<string>();modules.vehicles=(modules.vehicles||[]).filter((record,index)=>{if(!isObject(record)||!record.plate)return true;const plate=String(record.plate).replace(/[^a-z0-9]/gi,'').toUpperCase();if(!plate||!plates.has(plate)){if(plate)plates.add(plate);return true;}if(typeof record.id==='string')duplicateVehicleIds.add(record.id);quarantine.push({module:'vehicles',index,reason:'Placa duplicada; veículo, bem-base e dependências enviados para quarentena.'});return false;});
  if(duplicateVehicleIds.size)modules.assets=(modules.assets||[]).filter(record=>!isObject(record)||typeof record.id!=='string'||!duplicateVehicleIds.has(record.id));
  const bankAccountIds=new Set((modules.bank_accounts||[]).filter(isObject).map(record=>String(record.id)));
  for(const record of modules.transactions||[])if(isObject(record)&&typeof record.bank_account_id==='string'&&!bankAccountIds.has(record.bank_account_id)){record.legacy_bank_account_id=record.bank_account_id;record.bank_account_id=null;}
  const validKinds=new Set(['loc_mottus','rastrear','imoveis','holding']),companyById=new Map<string,string>(),companyByName=new Map<string,string>();for(const record of modules.companies||[])if(isObject(record)&&typeof record.id==='string'&&validKinds.has(String(record.kind))){companyById.set(record.id,record.id);companyByName.set(normalizedWord(record.name),record.id);}
  const categoryCompany=new Map((modules.categories||[]).filter(isObject).map(record=>[String(record.id),String(record.company_id)])),assetCompany=new Map((modules.assets||[]).filter(isObject).map(record=>[String(record.id),String(record.company_id)])),clientCompany=new Map((modules.clients||[]).filter(isObject).map(record=>[String(record.id),String(record.company_id)]));
  modules.transactions=(modules.transactions||[]).filter((record,index)=>{if(!isObject(record))return true;const evidence=new Set<string>();if(typeof record.company_id==='string'&&companyById.has(record.company_id))evidence.add(record.company_id);for(const key of ['company','empresa','unidade']){const id=companyByName.get(normalizedWord(record[key]));if(id)evidence.add(id);}for(const id of [categoryCompany.get(String(record.category_id)),assetCompany.get(String(record.asset_id)),clientCompany.get(String(record.client_id))])if(id&&companyById.has(id))evidence.add(id);if(evidence.size!==1){quarantine.push({module:'transactions',index,reason:evidence.size?'Referências de empresa conflitantes.':'Empresa não comprovável por referência explícita.'});return false;}record.company_id=[...evidence][0];return true;});
  if(!found.length)throw new Error('Versão não reconhecida: nenhum módulo conhecido foi localizado.');
  return{modules,quarantine,ignored,diagnostic:{...base,modulesFound:found,format:'legacy'}};
}

export function diagnoseRoot(root:unknown,encoding:string):Omit<BackupDiagnostic,'modulesFound'|'format'>{
  const rootType=Array.isArray(root)?'array':root===null?'other':typeof root==='object'?'object':typeof root==='string'?'string':'other';
  const object=isObject(root)?root:{},topLevelKeys=Object.keys(object).sort(),metadata=isObject(object.metadata)?object.metadata:{};
  const encrypted=Boolean(['encrypted','ciphertext','cipher','iv'].some(key=>key in object)||(typeof object.payload==='string'&&/^(U2FsdGVkX1|[A-Za-z0-9+/]{80,}={0,2})$/.test(object.payload)));
  return{encoding,rootType,topLevelKeys,version:String(object.version??metadata.version??'não informada'),metadataKeys:Object.keys(metadata).sort(),encrypted,serialized:typeof root==='string'};
}
