import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ExternalLink, X } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { getActiveAlerts } from '../components/AlertsPanel';

export default function Alertas() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const [version, setVersion] = useState(0); const [hidden, setHidden] = useState<string[]>(() => JSON.parse(sessionStorage.getItem('erp_hidden_alerts') || '[]'));
  useEffect(() => { const update = () => setVersion(v => v + 1); window.addEventListener('erp-data-updated', update); window.addEventListener('erp-transactions-updated', update); return () => { window.removeEventListener('erp-data-updated', update); window.removeEventListener('erp-transactions-updated', update); }; }, []);
  const all = getActiveAlerts(); const type = params.get('tipo');
  const alerts = useMemo(() => all.filter(alert => !hidden.includes(alert.id) && (!type || alert.type === type)), [all, hidden, type, version]);
  const hide = (id: string) => { const next = [...hidden, id]; setHidden(next); sessionStorage.setItem('erp_hidden_alerts', JSON.stringify(next)); };
  return <div className="space-y-6"><header><h1 className="flex items-center gap-2 font-display text-xl font-black"><AlertTriangle className="text-amber-600"/> Central de Alertas</h1><p className="text-xs text-secondary">Alertas desaparecem definitivamente apenas quando o cadastro relacionado é corrigido.</p></header><div className="flex flex-wrap gap-2"><button onClick={() => navigate('/alertas')} className="rounded border px-3 py-2 text-xs font-bold">Todos ({all.length})</button>{[...new Set(all.map(a => a.type))].map(item => <button key={item} onClick={() => navigate(`/alertas?tipo=${encodeURIComponent(item)}`)} className={`rounded border px-3 py-2 text-xs font-bold ${type === item ? 'bg-primary-container' : 'bg-white'}`}>{item}</button>)}</div><section className="space-y-3">{alerts.map(alert => <article key={alert.id} onClick={() => navigate(alert.route)} role="button" tabIndex={0} className="cursor-pointer rounded-xl border bg-white p-5 transition hover:border-primary"><div className="flex justify-between gap-4"><div><div className="flex gap-2"><span className={`rounded px-2 py-1 text-[10px] font-black uppercase ${alert.priority === 'alta' ? 'bg-red-100 text-red-700' : alert.priority === 'média' ? 'bg-amber-100 text-amber-700' : 'bg-blue-100 text-blue-700'}`}>{alert.priority}</span><span className="rounded bg-gray-100 px-2 py-1 text-[10px] font-black uppercase">{alert.type}</span></div><h2 className="mt-3 font-black">{alert.name}</h2><p className="text-xs">{alert.description}</p><div className="mt-2 flex flex-wrap gap-4 text-xs text-secondary"><span>Empresa: {alert.company}</span><span>Vencimento: {alert.due}</span><span>Status: {alert.status}</span></div></div><button onClick={event => { event.stopPropagation(); hide(alert.id); }} title="Ocultar durante esta sessão" aria-label="Ocultar alerta durante esta sessão"><X className="w-5"/></button></div><button onClick={event => { event.stopPropagation(); navigate(alert.route); }} className="mt-4 flex items-center gap-1 text-xs font-black text-primary"><ExternalLink className="w-4"/> Abrir cadastro correspondente</button></article>)}{!alerts.length && <div className="rounded-xl border bg-white p-8 text-center text-sm text-secondary">Nenhum alerta ativo neste filtro.</div>}</section></div>;
}
