import React,{useRef,useState}from'react';
import{Download,FileJson,ShieldCheck,Upload,X}from'lucide-react';
import Modal from'../components/Modal';
import{useAuth}from'../auth/AuthContext';
import{validateOwnerPassword}from'../services/adminValidation';
import{analyzeBackupBytes,analyzeBackupZip,BackupAnalysis,createMasterBackup,createMasterBackupZip,sha256}from'../services/backupMaster';
import{createRestorePlan,executeRestorePlan,RestorePlan}from'../services/restoreValidation';
import{repository}from'../repositories';

type Analysis={result:BackupAnalysis;file:{name:string;size:number;hash:string}};
const download=async(name:string,value:unknown):Promise<void>=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.style.display='none';document.body.appendChild(anchor);anchor.click();anchor.remove();await new Promise<void>(resolve=>window.setTimeout(resolve,0));URL.revokeObjectURL(url);};
const downloadZip=async(name:string,buffer:ArrayBuffer):Promise<void>=>{const url=URL.createObjectURL(new Blob([buffer],{type:'application/zip'})),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.style.display='none';document.body.appendChild(anchor);anchor.click();anchor.remove();await new Promise<void>(resolve=>window.setTimeout(resolve,0));URL.revokeObjectURL(url);};

const BoundaryBase=React.Component as any;
class BackupBoundary extends BoundaryBase{state={error:''};static getDerivedStateFromError(error:unknown){return{error:error instanceof Error?error.message:'Falha inesperada no módulo.'};}render(){return this.state.error?<div className="rounded-xl border border-red-200 bg-white p-8"><h1 className="font-black text-red-700">Falha ao abrir o Backup</h1><p className="mt-2 text-sm">{this.state.error}</p><button type="button" onClick={()=>window.location.reload()} className="mt-4 rounded bg-primary-container px-4 py-2 text-xs font-black">RECARREGAR</button></div>:this.props.children;}}

export default function Backup(){return <BackupBoundary><BackupContent/></BackupBoundary>}
function BackupContent(){
 const{profile}=useAuth(),inputRef=useRef<HTMLInputElement>(null);
 const[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[analysis,setAnalysis]=useState<Analysis|null>(null),[plan,setPlan]=useState<RestorePlan|null>(null),[stage,setStage]=useState('Arquivo selecionado'),[authOpen,setAuthOpen]=useState(false),[password,setPassword]=useState(''),[phrase,setPhrase]=useState(''),[confirmed,setConfirmed]=useState(false);
 const exportMaster=async()=>{setBusy(true);setMessage('');try{const backup=await createMasterBackupZip();await downloadZip(`grupo-3a-backup-master-${new Date().toISOString().slice(0,10)}.zip`,backup.buffer);setMessage(`Exportado: ${backup.total} registros · SHA-256 ${backup.sha256}`);}catch(error){setMessage(error instanceof Error?error.message:'Falha ao exportar.');}finally{setBusy(false);}};
 const analyze=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setBusy(true);setStage('Validando');setMessage('');setAnalysis(null);setPlan(null);try{const name=file.name.toLowerCase();if(!name.endsWith('.json')&&!name.endsWith('.zip'))throw new Error('Selecione um arquivo .json ou .zip.');const buffer=await file.arrayBuffer(),hash=await sha256(buffer),result=name.endsWith('.zip')?await analyzeBackupZip(buffer):await analyzeBackupBytes(buffer),nextPlan=await createRestorePlan(repository,result,hash);setAnalysis({result,file:{name:file.name,size:file.size,hash}});setPlan(nextPlan);setStage(nextPlan.ready?'Pronto para restaurar':'Correções necessárias');}catch(error){setStage('Falhou e foi revertido');setMessage(error instanceof Error?error.message:'Versão não reconhecida.');event.target.value='';}finally{setBusy(false);}};
 const cancel=()=>{setAnalysis(null);setPlan(null);setMessage('');setStage('Arquivo selecionado');if(inputRef.current)inputRef.current.value='';};
 const report=()=>analysis&&plan?{format:'GRUPO_3A_ERP_DRY_RUN_REPORT',generatedAt:new Date().toISOString(),mode:'new_only',file:analysis.file,diagnostic:analysis.result.diagnostic,validation:plan.summary,restorationBlocked:!plan.ready}:null;
 const restoreNow=async(event:React.FormEvent)=>{event.preventDefault();if(busy)return;if(!analysis||!plan?.ready||!plan.summary.consistent||plan.summary.criticalErrors>0)return setMessage('O plano válido e consistente precisa ser recalculado.');if(profile?.role!=='owner')return setMessage('A restauração exige perfil owner ativo.');if(!confirmed)return setMessage('Confirme a política new_only.');if(phrase.trim()!=='RESTAURAR BACKUP')return setMessage('Digite exatamente RESTAURAR BACKUP.');setBusy(true);setMessage('');try{setStage('Autenticando owner');const auth=await validateOwnerPassword(password);setPassword('');if(!auth.valid)throw new Error(auth.message);setStage('Criando backup de segurança');const safetyBackup=await createMasterBackup();await download(`grupo-3a-backup-seguranca-${plan.operationId}.json`,safetyBackup);setStage('Backup de segurança criado');await new Promise<void>(resolve=>window.setTimeout(resolve,0));setStage('Iniciando restauração');await new Promise<void>(resolve=>window.setTimeout(resolve,0));setStage('Processando lote 1 de 1');const result=await executeRestorePlan(repository,plan);setStage('Validando totais inseridos');if(result.status!=='completed'||result.inserted!==plan.willInsert)throw new Error(`Validação final divergente: ${result.inserted} de ${plan.willInsert} operações.`);const finalReport={...report(),operation:result};await download(`grupo-3a-restauracao-${plan.operationId}.json`,finalReport);setStage('Concluído');setAuthOpen(false);}catch(error){setStage('Falhou e foi revertido');setMessage(error instanceof Error?error.message:'Restauração bloqueada.');}finally{setBusy(false);}};
 return <div className="space-y-6 pb-12"><header className="border-b pb-4"><h1 className="font-display text-lg font-black">Backup do Sistema</h1><p className="text-xs text-secondary">Exportação e diagnóstico seguro do novo ERP.</p></header>
  <section className="rounded-xl border bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="text-primary"/><div><h2 className="font-display font-black">BACKUP MASTER</h2><p className="text-xs text-secondary">Acesso exclusivo do proprietário · modo new_only</p></div></div><input ref={inputRef} hidden type="file" accept=".json,.zip,application/json,application/zip" onChange={analyze}/><div className="mt-6 flex flex-wrap gap-3"><button type="button" disabled={busy} onClick={exportMaster} className="flex items-center gap-2 rounded bg-primary-container px-5 py-3 text-xs font-black disabled:opacity-50"><Download className="w-4"/> EXPORTAR BACKUP MASTER</button><button type="button" disabled={busy} onClick={()=>inputRef.current?.click()} className="flex items-center gap-2 rounded bg-inverse-surface px-5 py-3 text-xs font-black text-white disabled:opacity-50"><Upload className="w-4"/> IMPORTAR BACKUP MASTER</button></div>{busy&&<p className="mt-4 text-xs font-bold">Processando, aguarde...</p>}{message&&<p className="mt-4 rounded border bg-amber-50 p-3 text-xs">{message}</p>}</section>
  <p className="rounded border bg-white p-3 text-xs font-black uppercase">Estado: {stage}</p>{analysis&&plan&&<DryRun analysis={analysis} plan={plan} busy={busy} cancel={cancel} downloadReport={()=>{void download(`grupo-3a-dry-run-${new Date().toISOString().slice(0,10)}.json`,report());}} requestImport={()=>plan.ready&&setAuthOpen(true)}/>} 
  <Modal isOpen={authOpen} onClose={()=>{setAuthOpen(false);setPassword('');setPhrase('');setConfirmed(false)}} title="Confirmar restauração owner"><form onSubmit={restoreNow} className="space-y-4"><p className="text-xs">Nenhum registro existente será substituído.</p><label className="block text-xs font-bold">Senha atual<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full border p-3"/></label><label className="block text-xs font-bold">Digite RESTAURAR BACKUP<input required value={phrase} onChange={e=>setPhrase(e.target.value)} className="mt-1 w-full border p-3"/></label><label className="flex gap-2 text-xs"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Confirmo a restauração somente dos registros válidos.</label><button disabled={busy||!plan?.ready||!confirmed||phrase!=='RESTAURAR BACKUP'} className="w-full bg-primary-container p-3 font-black disabled:opacity-50">RESTAURAR REGISTROS VÁLIDOS</button></form></Modal>
 </div>;
}

function DryRun({analysis,plan,busy,cancel,downloadReport,requestImport}:{analysis:Analysis;plan:RestorePlan;busy:boolean;cancel:()=>void;downloadReport:()=>void;requestImport:()=>void}){const{result,file}=analysis,summary=plan?.summary;if(!summary||!Array.isArray(summary.modules)||!Array.isArray(summary.errorGroups))return <section className="rounded-xl border border-amber-200 bg-white p-6"><h2 className="font-black">Resultado anterior incompatível</h2><p className="mt-2 text-xs text-secondary">Selecione novamente o arquivo para gerar o resultado canônico.</p><button type="button" onClick={cancel} className="mt-4 rounded bg-primary-container px-4 py-2 text-xs font-black">SELECIONAR NOVAMENTE</button></section>;return <section className="space-y-5 rounded-xl border bg-white p-6"><div className="flex justify-between"><div><h2 className="flex items-center gap-2 font-black"><FileJson className="w-5"/> Dry-run concluído</h2><p className="text-xs text-secondary">Nenhum registro foi importado.</p></div><button type="button" onClick={cancel} aria-label="Cancelar"><X/></button></div>
 <dl className="grid gap-3 text-xs md:grid-cols-3"><Info label="Arquivo" value={file.name}/><Info label="Tamanho" value={`${(file.size/1024).toFixed(2)} KB`}/><Info label="Formato" value={result.diagnostic.format}/><Info label="Versão" value={result.diagnostic.version}/><Info label="Metadados" value={result.diagnostic.metadataPath||'JSON único'}/><Info label="Módulos" value={result.diagnostic.modulesFound.join(', ')}/></dl>
 <div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-gray-50 text-left"><tr><th className="p-3">Módulo</th><th>Total</th><th>Válidos</th><th>Duplicados</th><th>Conflitos</th><th>Inválidos</th></tr></thead><tbody>{summary.modules.map(row=><tr key={row.module} className="border-t"><td className="p-3 font-bold">{row.module}</td><td>{row.total}</td><td>{row.valid}</td><td>{row.duplicates}</td><td>{row.conflicts}</td><td>{row.invalid}</td></tr>)}</tbody></table></div>
 <div className="grid gap-3 text-xs md:grid-cols-3"><Info label="Registros do backup" value={summary.total}/><Info label="Registros válidos do backup" value={summary.ready}/><Info label="Registros em quarentena" value={summary.quarantine}/><Info label="Registros técnicos adicionais" value={summary.technicalGenerated}/><Info label="Operações previstas" value={summary.plannedOperations}/><Info label="Ignorados" value={summary.ignored}/><Info label="Consistência" value={summary.consistent?'Aprovada':'Reprovada'}/><Info label="Política" value="new_only"/></div>
 {!!summary.errorGroups.length&&<div className="overflow-x-auto"><h3 className="mb-2 font-black">Erros agrupados</h3><table className="w-full text-xs"><thead className="bg-red-50 text-left"><tr><th className="p-3">Módulo</th><th>Campo</th><th>Motivo</th><th>Quantidade</th></tr></thead><tbody>{summary.errorGroups.map(group=><tr key={`${group.module}-${group.field}-${group.code}`} className="border-t"><td className="p-3">{group.module}</td><td>{group.field}</td><td>{group.reason}</td><td>{group.quantity}</td></tr>)}</tbody></table></div>}
 {!plan.ready&&<p className="rounded bg-red-50 p-3 text-xs font-bold text-red-700">Restauração bloqueada: {summary.criticalErrors} erros globais; {summary.errorGroups.length} grupos individuais.</p>}
 <div className="flex flex-wrap gap-3"><button onClick={cancel} className="rounded border px-4 py-2 text-xs font-bold">Cancelar</button><button onClick={downloadReport} className="rounded border px-4 py-2 text-xs font-bold">Baixar relatório</button><button disabled={busy||!plan.ready} onClick={requestImport} className="rounded bg-primary-container px-4 py-2 text-xs font-black disabled:opacity-50">Restaurar somente os válidos</button></div></section>;}
function Info({label,value}:{label:string;value:React.ReactNode}){return <div><dt className="font-bold">{label}</dt><dd className="break-words">{value}</dd></div>}
