import React,{useRef,useState}from'react';
import{Download,FileCheck2,FileJson,Upload}from'lucide-react';
import{analyzeBackupBytes,analyzeBackupZip,backupModules,createMasterBackupJson,createMasterBackupZip,sha256,type BackupAnalysis}from'../services/backupMaster';
import{createRestorePlan,type RestorePlan}from'../services/restoreValidation';
import{repository,type RepositoryModule}from'../repositories';

const saveBlob=async(name:string,blob:Blob)=>{const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;document.body.appendChild(anchor);anchor.click();anchor.remove();await new Promise(resolve=>setTimeout(resolve,0));URL.revokeObjectURL(url)};
const saveJson=(name:string,value:unknown)=>saveBlob(name,new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));
type DryRun={analysis:BackupAnalysis;plan:RestorePlan;file:{name:string;size:number;sha256:string}};
type BackupHistory={id:string;kind:'JSON'|'ZIP';createdAt:string;modules:number;records:number;size:number;status:'concluído';sha256:string};
const HISTORY_KEY='grupo3a_backup_history';
export default function Backup(){
  const[selected,setSelected]=useState<RepositoryModule[]>(backupModules);
  const[busy,setBusy]=useState(false);
  const[message,setMessage]=useState('');
  const[dryRun,setDryRun]=useState<DryRun|null>(null);
  const[history,setHistory]=useState<BackupHistory[]>(()=>{try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')as BackupHistory[]}catch{return[]}});
  const inputRef=useRef<HTMLInputElement>(null);
  const run=async(action:()=>Promise<void>)=>{setBusy(true);setMessage('');try{await action()}catch(reason){setMessage(reason instanceof Error?reason.message:'Operação não concluída.')}finally{setBusy(false)}};
  const remember=(item:BackupHistory)=>{const next=[item,...history].slice(0,50);setHistory(next);localStorage.setItem(HISTORY_KEY,JSON.stringify(next))};
  const snapshot=()=>run(async()=>{if(!selected.length)throw new Error('Selecione ao menos um módulo.');const result=await createMasterBackupJson(selected),blob=new Blob([result.json],{type:'application/json'});await saveBlob(`grupo-3a-backup-master-${new Date().toISOString().slice(0,10)}.json`,blob);remember({id:crypto.randomUUID(),kind:'JSON',createdAt:new Date().toISOString(),modules:selected.length,records:result.totalRecords,size:result.size,status:'concluído',sha256:result.sha256});setMessage(`Backup Master JSON concluído · ${result.totalRecords} registros · SHA-256 ${result.sha256}`)});
  const exportZip=()=>run(async()=>{if(!selected.length)throw new Error('Selecione ao menos um módulo.');const backup=await createMasterBackupZip(selected),blob=new Blob([backup.buffer],{type:'application/zip'});await saveBlob(`grupo-3a-backup-master-${new Date().toISOString().slice(0,10)}.zip`,blob);remember({id:crypto.randomUUID(),kind:'ZIP',createdAt:new Date().toISOString(),modules:selected.length,records:backup.total,size:blob.size,status:'concluído',sha256:backup.sha256});setMessage(`Backup exportado · ${backup.total} transações · SHA-256 ${backup.sha256}`)});
  const analyze=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;await run(async()=>{const bytes=await file.arrayBuffer(),hash=await sha256(bytes),analysis=file.name.toLowerCase().endsWith('.zip')?await analyzeBackupZip(bytes):await analyzeBackupBytes(bytes),plan=await createRestorePlan(repository,analysis,hash);setDryRun({analysis,plan,file:{name:file.name,size:file.size,sha256:hash}});setMessage('Dry-run concluído. Nenhum registro foi gravado.')});event.target.value=''};
  const report=dryRun?{format:'GRUPO_3A_ERP_DRY_RUN_REPORT',generatedAt:new Date().toISOString(),mode:'new_only',file:dryRun.file,diagnostic:dryRun.analysis.diagnostic,quarantine:dryRun.analysis.adapterQuarantine,validation:dryRun.plan.summary,restorationBlocked:true,reason:'Database em modo somente leitura; rollback transacional multi-tabela indisponível no schema existente.'}:null;
  return <div className="space-y-6">
    <header><h1 className="font-display text-lg font-black">Backup Master</h1><p className="text-xs text-secondary">Exportação real, validação e dry-run sem gravação remota.</p></header>
    <section className="rounded-xl border bg-white p-6"><div className="flex gap-2"><button onClick={()=>setSelected(backupModules)} className="rounded border px-3 py-2 text-xs font-bold">SELECIONAR TUDO</button><button onClick={()=>setSelected([])} className="rounded border px-3 py-2 text-xs font-bold">LIMPAR SELEÇÃO</button></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{backupModules.map(module=><label key={module} className="flex items-center gap-2 rounded border p-2 text-xs"><input type="checkbox" checked={selected.includes(module)} onChange={event=>setSelected(current=>event.target.checked?[...current,module]:current.filter(item=>item!==module))}/>{module}</label>)}</div><input ref={inputRef} hidden type="file" accept=".json,.zip,application/json,application/zip" onChange={analyze}/><div className="mt-5 flex flex-wrap gap-3"><button disabled={busy||!selected.length} onClick={snapshot} className="flex items-center gap-2 rounded border px-4 py-3 text-xs font-black disabled:opacity-40"><FileJson className="h-4 w-4"/>GERAR SNAPSHOT</button><button disabled={busy||!selected.length} onClick={exportZip} className="flex items-center gap-2 rounded bg-primary-container px-4 py-3 text-xs font-black disabled:opacity-40"><Download className="h-4 w-4"/>BAIXAR BACKUP</button><button disabled={busy} onClick={()=>inputRef.current?.click()} className="flex items-center gap-2 rounded bg-black px-4 py-3 text-xs font-black text-white disabled:opacity-40"><Upload className="h-4 w-4"/>VALIDAR / DRY-RUN</button></div>{busy&&<p className="mt-4 text-xs font-bold">Processando...</p>}{message&&<p className="mt-4 rounded bg-amber-50 p-3 text-xs">{message}</p>}</section>
    {dryRun&&<section className="space-y-4 rounded-xl border bg-white p-6"><h2 className="flex items-center gap-2 font-black"><FileCheck2 className="h-5 w-5"/>Dry-run new_only</h2><div className="grid gap-3 text-xs md:grid-cols-3"><Info label="Arquivo" value={dryRun.file.name}/><Info label="SHA-256" value={dryRun.file.sha256}/><Info label="Formato" value={dryRun.analysis.diagnostic.format}/><Info label="Registros" value={dryRun.plan.summary.total}/><Info label="Novos válidos" value={dryRun.plan.summary.ready}/><Info label="Duplicados" value={dryRun.plan.summary.duplicates}/><Info label="Conflitos" value={dryRun.plan.summary.conflicts}/><Info label="Quarentena" value={dryRun.plan.summary.quarantine}/><Info label="Operações previstas" value={dryRun.plan.summary.plannedOperations}/></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b"><th className="p-2">Módulo</th><th>Total</th><th>Válidos</th><th>Duplicados</th><th>Conflitos</th><th>Inválidos</th></tr></thead><tbody>{dryRun.plan.summary.modules.map(row=><tr key={row.module} className="border-b"><td className="p-2">{row.module}</td><td>{row.total}</td><td>{row.valid}</td><td>{row.duplicates}</td><td>{row.conflicts}</td><td>{row.invalid}</td></tr>)}</tbody></table></div><p className="rounded bg-gray-50 p-3 text-xs">Restauração real bloqueada: o schema atual não oferece transação/rollback multi-tabela compatível, e esta etapa não permite criar RPC.</p><button onClick={()=>void saveJson(`grupo-3a-dry-run-${new Date().toISOString().slice(0,10)}.json`,report)} className="rounded border px-4 py-2 text-xs font-bold">BAIXAR RELATÓRIO</button></section>}
    <section className="rounded-xl border bg-white p-6"><h2 className="font-black">Histórico local de backups</h2>{history.length===0?<p className="mt-3 text-xs text-secondary">Nenhuma cópia gerada neste navegador.</p>:<div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b"><th className="p-2">Data/hora</th><th>Formato</th><th>Registros</th><th>Tamanho</th><th>SHA-256</th></tr></thead><tbody>{history.map(item=><tr key={item.id} className="border-b"><td className="p-2">{new Date(item.createdAt).toLocaleString('pt-BR')}</td><td>{item.kind}</td><td>{item.records??'—'}</td><td>{item.size?`${(item.size/1024).toLocaleString('pt-BR',{maximumFractionDigits:1})} KB`:'—'}</td><td className="max-w-64 break-all font-mono text-[10px]">{item.sha256}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
function Info({label,value}:{label:string;value:React.ReactNode}){return <div><b>{label}</b><p className="break-all">{value}</p></div>}
