import React,{useEffect,useMemo,useState}from'react';
import{Calendar,ChevronLeft,ChevronRight,Search,X}from'lucide-react';
import{repository,type EntityRecord}from'../repositories';
import{chargeAgendaDryRun,enrichChargeToAgenda,type AgendaCharge}from'../services/chargeAgendaAdapter';

type ChargeRow=AgendaCharge&{received_at?:string;ref?:string};
type NamedRow=EntityRecord&{name?:string};
const brl=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const iso=(date:Date)=>{const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)};
const monthKey=(date:Date)=>iso(new Date(date.getFullYear(),date.getMonth(),1)).slice(0,7);
export default function CalendarioCobranca(){
  const[cursor,setCursor]=useState(()=>new Date());
  const[selectedDay,setSelectedDay]=useState('');
  const[charges,setCharges]=useState<ChargeRow[]>([]);
  const[companies,setCompanies]=useState<NamedRow[]>([]);
  const[categories,setCategories]=useState<NamedRow[]>([]);
  const[search,setSearch]=useState('');
  const[status,setStatus]=useState('todos');
  const[company,setCompany]=useState('todas');
  const[client,setClient]=useState('todos');
  const[start,setStart]=useState('');
  const[end,setEnd]=useState('');
  const[loading,setLoading]=useState(true);
  const[error,setError]=useState('');
  useEffect(()=>{let active=true;Promise.all([repository.list<ChargeRow>('charges'),repository.list<NamedRow>('companies'),repository.list<NamedRow>('categories'),repository.list<EntityRecord>('clients'),repository.list<EntityRecord>('properties'),repository.list<EntityRecord>('vehicles')]).then(([chargeRows,companyRows,categoryRows,clientRows,propertyRows,vehicleRows])=>{if(!active)return;setCharges(chargeRows.map(row=>enrichChargeToAgenda(row,{clients:clientRows,properties:propertyRows,vehicles:vehicleRows})));setCompanies(companyRows);setCategories(categoryRows)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'Não foi possível carregar as cobranças.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const companyNames=useMemo(()=>new Map(companies.map(item=>[item.id,item.name||''])),[companies]);
  const categoryNames=useMemo(()=>new Map(categories.map(item=>[item.id,item.name||''])),[categories]);
  const clients=useMemo(()=>[...new Set(charges.map(item=>item.client_name).filter((value):value is string=>Boolean(value)))].sort(),[charges]);
  const filtered=charges.filter(charge=>{const date=String(charge.due_date||''),term=search.trim().toLowerCase();return(status==='todos'||charge.status===status)&&(company==='todas'||charge.company_id===company)&&(client==='todos'||charge.client_name===client)&&(!start||date>=start)&&(!end||date<=end)&&(!term||[charge.description,charge.client_name,charge.ref,charge.observation,companyNames.get(String(charge.company_id||'')),categoryNames.get(String(charge.category_id||''))].some(value=>String(value||'').toLowerCase().includes(term)))});
  const monthCharges=filtered.filter(charge=>String(charge.due_date||'').startsWith(monthKey(cursor)));
  const byDay=useMemo(()=>{const map=new Map<string,ChargeRow[]>();for(const charge of filtered){const date=String(charge.due_date||'');map.set(date,[...(map.get(date)||[]),charge])}return map},[filtered]);
  const calendarDays=useMemo(()=>{const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),startDate=new Date(cursor.getFullYear(),cursor.getMonth(),1-first.getDay());return Array.from({length:42},(_,index)=>{const date=new Date(startDate);date.setDate(startDate.getDate()+index);return date})},[cursor]);
  const today=iso(new Date()),weekEnd=iso(new Date(Date.now()+7*86400000));
  const dayCharges=selectedDay?byDay.get(selectedDay)||[]:[];
  const received=monthCharges.filter(charge=>charge.status==='pago').reduce((sum,charge)=>sum+Number(charge.value||0),0);
  const pending=monthCharges.filter(charge=>charge.status!=='pago').reduce((sum,charge)=>sum+Number(charge.value||0),0);
  const audit=useMemo(()=>chargeAgendaDryRun(charges,charges),[charges]);
  return <div className="space-y-6">
    <header><h2 className="font-display text-lg font-black">Agenda de Cobranças</h2><p className="text-xs text-secondary">Calendário real, paginado e sem criação automática de cobranças.</p></header>
    {!loading&&!error&&<p className={`rounded-lg border p-3 text-xs ${audit.consistent?'border-green-200 bg-green-50 text-green-800':'border-red-200 bg-red-50 text-red-800'}`}>Dry-run da Escala: {audit.source} em charges → {audit.calendar} no calendário · duplicados {audit.duplicates} · inválidos {audit.invalid} · zero gravações.</p>}
    <section className="grid gap-2 rounded-xl border bg-white p-4 md:grid-cols-7"><label className="relative md:col-span-2"><Search className="absolute left-3 top-2.5 h-4 w-4"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar cobrança" className="w-full rounded border py-2 pl-9 pr-3 text-xs"/></label><select value={company} onChange={event=>setCompany(event.target.value)} className="rounded border p-2 text-xs"><option value="todas">Todas as empresas</option>{companies.map(item=><option key={item.id} value={item.id}>{item.name||item.id}</option>)}</select><select value={client} onChange={event=>setClient(event.target.value)} className="rounded border p-2 text-xs"><option value="todos">Todos os clientes</option>{clients.map(name=><option key={name}>{name}</option>)}</select><select value={status} onChange={event=>setStatus(event.target.value)} className="rounded border p-2 text-xs"><option value="todos">Todos os status</option><option value="pago">Pagas</option><option value="pendente">Pendentes</option><option value="vencido">Vencidas</option></select><input type="date" value={start} onChange={event=>setStart(event.target.value)} className="rounded border p-2 text-xs"/><input type="date" value={end} onChange={event=>setEnd(event.target.value)} className="rounded border p-2 text-xs"/></section>
    <section className="grid gap-4 md:grid-cols-3"><article className="rounded-xl border bg-white p-5"><small>Cobranças no mês</small><b className="block text-xl">{monthCharges.length}</b></article><article className="rounded-xl border bg-white p-5"><small>Recebido</small><b className="block">{brl(received)}</b></article><article className="rounded-xl border bg-white p-5"><small>Pendente</small><b className="block">{brl(pending)}</b></article></section>
    {loading&&<p className="rounded-xl border bg-white p-6 text-xs">Carregando cobranças...</p>}{error&&<p className="rounded-xl border border-red-200 bg-red-50 p-4 text-xs text-red-700">{error}</p>}
    {!loading&&!error&&<section className="rounded-xl border bg-white p-4"><div className="mb-4 flex items-center justify-center gap-4"><button onClick={()=>setCursor(value=>new Date(value.getFullYear(),value.getMonth()-1,1))} className="rounded border p-2"><ChevronLeft className="h-4 w-4"/></button><div className="min-w-48 text-center font-black capitalize"><Calendar className="mr-2 inline h-4 w-4"/>{cursor.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</div><button onClick={()=>setCursor(value=>new Date(value.getFullYear(),value.getMonth()+1,1))} className="rounded border p-2"><ChevronRight className="h-4 w-4"/></button></div><div className="grid grid-cols-7 text-center text-[10px] font-bold uppercase">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(day=><div key={day} className="p-2">{day}</div>)}</div><div className="grid grid-cols-7">{calendarDays.map(date=>{const key=iso(date),items=byDay.get(key)||[],outside=date.getMonth()!==cursor.getMonth(),pendingWeek=key>=today&&key<=weekEnd&&items.some(item=>item.status!=='pago');return <button key={key} onClick={()=>setSelectedDay(key)} className={`min-h-24 border p-2 text-left ${outside?'bg-gray-50 text-gray-400':'bg-white'} ${pendingWeek?'ring-2 ring-inset ring-amber-400':''}`}><span className="text-xs font-bold">{date.getDate()}</span>{items.slice(0,3).map(item=><span key={item.id} className={`mt-1 block truncate rounded px-1 py-0.5 text-[9px] ${item.status==='pago'?'bg-green-100 text-green-800':'bg-amber-100 text-amber-900'}`}>{item.client_name||item.description||'Cobrança'} · {brl(Number(item.value||0))}</span>)}{items.length>3&&<span className="text-[9px]">+{items.length-3}</span>}</button>})}</div></section>}
    {!loading&&!error&&monthCharges.length===0&&<p className="rounded-xl border bg-white p-6 text-xs text-secondary">Nenhum registro.</p>}
    {selectedDay&&<><div className="fixed inset-0 z-40 bg-black/30" onClick={()=>setSelectedDay('')}/><aside className="fixed right-0 top-0 z-50 h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><button onClick={()=>setSelectedDay('')} className="float-right"><X/></button><h3 className="font-display font-black">Cobranças de {selectedDay}</h3><p className="mb-5 text-xs text-secondary">{dayCharges.length} registro(s)</p>{dayCharges.length===0&&<p className="rounded border p-4 text-xs">Nenhum registro.</p>}<div className="space-y-3">{dayCharges.map(charge=><article key={charge.id} className="rounded border p-4"><div className="flex justify-between gap-3"><div><b>{charge.client_name||'Cliente não informado'}</b><p className="text-xs">{charge.ref||charge.description||'Cobrança sem descrição'}</p><p className="text-xs text-secondary">{companyNames.get(String(charge.company_id||''))||'Empresa não vinculada'} · {categoryNames.get(String(charge.category_id||''))||'Categoria não vinculada'} · {charge.status||'Status não informado'}</p></div><b>{brl(Number(charge.value||0))}</b></div><div className="mt-3 flex gap-2"><button disabled title="Pagamento bloqueado até existir autorização owner/admin server-side e vínculo transacional seguro." className="rounded border px-3 py-2 text-xs opacity-40">Pagar</button><button disabled title="Edição bloqueada até o schema completo e permissões serem confirmados." className="rounded border px-3 py-2 text-xs opacity-40">Editar</button><button disabled title="Exclusão bloqueada: não existe Log de Exclusões remoto compatível." className="rounded border px-3 py-2 text-xs text-red-700 opacity-40">Excluir</button></div></article>)}</div></aside></>}
  </div>;
}
