import React,{useEffect,useMemo,useState}from'react';
import{Calendar,ChevronLeft,ChevronRight,Search,X}from'lucide-react';
import{repository,type EntityRecord}from'../repositories';
import{chargeAgendaDryRun,enrichChargeToAgenda,type AgendaCharge}from'../services/chargeAgendaAdapter';
import ProtectedRecordActions from'../components/ProtectedRecordActions';
import PayChargeButton from'../components/PayChargeButton';
import{generateAgendaPropertyReceipt}from'../services/agendaPropertyReceipt';
type ChargeRow=AgendaCharge&{received_at?:string;ref?:string};
type NamedRow=EntityRecord&{name?:string};
const brl=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const iso=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,10);
export default function CalendarioCobranca(){
 const[cursor,setCursor]=useState(new Date()),[selectedDay,setSelectedDay]=useState(''),[charges,setCharges]=useState<ChargeRow[]>([]),[companies,setCompanies]=useState<NamedRow[]>([]),[categories,setCategories]=useState<NamedRow[]>([]),[properties,setProperties]=useState<EntityRecord[]>([]);
 const[search,setSearch]=useState(''),[status,setStatus]=useState('todos'),[company,setCompany]=useState('todas'),[client,setClient]=useState('todos'),[start,setStart]=useState(''),[end,setEnd]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[version,setVersion]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);Promise.all([repository.list<ChargeRow>('charges'),repository.list<NamedRow>('companies'),repository.list<NamedRow>('categories'),repository.list<EntityRecord>('clients'),repository.list<EntityRecord>('properties'),repository.list<EntityRecord>('vehicles')]).then(([rows,cos,cats,clients,propertyRows,vehicles])=>{if(active){setCharges(rows.map(row=>enrichChargeToAgenda(row,{clients,properties:propertyRows,vehicles})));setCompanies(cos);setCategories(cats);setProperties(propertyRows)}}).catch(reason=>active&&setError(reason instanceof Error?reason.message:'Falha ao carregar cobranças.')).finally(()=>active&&setLoading(false));return()=>{active=false}},[version]);
 const companyNames=useMemo(()=>new Map(companies.map(item=>[item.id,item.name||''])),[companies]),categoryNames=useMemo(()=>new Map(categories.map(item=>[item.id,item.name||''])),[categories]);
 const clients=useMemo(()=>[...new Set(charges.map(item=>item.client_name).filter(Boolean))].sort(),[charges]);
 const filtered=charges.filter(charge=>{const date=charge.due_date,term=search.toLowerCase();return(status==='todos'||charge.status===status)&&(company==='todas'||charge.company_id===company)&&(client==='todos'||charge.client_name===client)&&(!start||date>=start)&&(!end||date<=end)&&(!term||[charge.description,charge.client_name,charge.ref].some(value=>String(value||'').toLowerCase().includes(term)))});
 const month=`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}`,monthCharges=filtered.filter(charge=>charge.due_date.startsWith(month));
 const byDay=useMemo(()=>{const map=new Map<string,ChargeRow[]>();for(const charge of filtered)map.set(charge.due_date,[...(map.get(charge.due_date)||[]),charge]);return map},[filtered]);
 const first=new Date(cursor.getFullYear(),cursor.getMonth(),1),calendarStart=new Date(cursor.getFullYear(),cursor.getMonth(),1-first.getDay()),days=Array.from({length:42},(_,index)=>{const date=new Date(calendarStart);date.setDate(calendarStart.getDate()+index);return date});
 const today=iso(new Date()),weekEnd=iso(new Date(Date.now()+7*86400000)),dayCharges=byDay.get(selectedDay)||[],audit=chargeAgendaDryRun(charges,charges);
 return <div className="space-y-5">
  <header><h2 className="font-display text-lg font-black">Agenda de Cobranças</h2><p className="text-xs text-secondary">Tabela charges adaptada diretamente, sem duplicação.</p></header>
  {!loading&&<p className={`rounded border p-3 text-xs ${audit.consistent?'bg-green-50 text-green-800':'bg-red-50 text-red-800'}`}>{audit.source} registros em charges → {audit.calendar} no calendário · duplicados {audit.duplicates}</p>}
  <section className="grid gap-2 rounded-xl border bg-white p-4 md:grid-cols-7"><label className="relative md:col-span-2"><Search className="absolute left-3 top-2.5 h-4 w-4"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar" className="w-full rounded border py-2 pl-9 text-xs"/></label><select value={company} onChange={e=>setCompany(e.target.value)} className="rounded border p-2 text-xs"><option value="todas">Todas empresas</option>{companies.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={client} onChange={e=>setClient(e.target.value)} className="rounded border p-2 text-xs"><option value="todos">Todos clientes</option>{clients.map(name=><option key={name}>{name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded border p-2 text-xs"><option value="todos">Todos status</option><option value="pago">Pagas</option><option value="pendente">Pendentes</option><option value="vencido">Vencidas</option></select><input type="date" value={start} onChange={e=>setStart(e.target.value)} className="rounded border p-2 text-xs"/><input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="rounded border p-2 text-xs"/></section>
  <section className="grid gap-3 md:grid-cols-3"><Card label="Cobranças no mês" value={String(monthCharges.length)}/><Card label="Recebido" value={brl(monthCharges.filter(row=>row.status==='pago').reduce((sum,row)=>sum+row.value,0))}/><Card label="Pendente" value={brl(monthCharges.filter(row=>row.status!=='pago').reduce((sum,row)=>sum+row.value,0))}/></section>
  {loading&&<p>Carregando...</p>}{error&&<p className="text-red-700">{error}</p>}{!loading&&!error&&<section className="rounded-xl border bg-white p-4"><div className="mb-4 flex items-center justify-center gap-4"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}><ChevronLeft/></button><b className="capitalize"><Calendar className="mr-2 inline h-4 w-4"/>{cursor.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</b><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}><ChevronRight/></button></div><div className="grid grid-cols-7 text-center text-[10px] font-bold">{['DOM','SEG','TER','QUA','QUI','SEX','SÁB'].map(day=><div key={day}>{day}</div>)}</div><div className="grid grid-cols-7">{days.map(date=>{const key=iso(date),items=byDay.get(key)||[],highlight=key>=today&&key<=weekEnd&&items.some(item=>item.status==='pendente');return <button key={key} onClick={()=>setSelectedDay(key)} className={`min-h-24 border p-2 text-left ${date.getMonth()!==cursor.getMonth()?'bg-gray-50 text-gray-400':''} ${highlight?'ring-2 ring-inset ring-amber-400':''}`}><b className="text-xs">{date.getDate()}</b>{items.slice(0,3).map(item=><span key={item.id} className="mt-1 block truncate rounded bg-amber-50 px-1 text-[9px]">{item.ref||item.client_name} · {brl(item.value)}</span>)}</button>})}</div></section>}
  {selectedDay&&<><div className="fixed inset-0 z-40 bg-black/30" onClick={()=>setSelectedDay('')}/><aside className="fixed right-0 top-0 z-50 h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><button onClick={()=>setSelectedDay('')} className="float-right"><X/></button><h3 className="font-black">Cobranças de {selectedDay}</h3><div className="mt-5 space-y-3">{dayCharges.map(charge=>{const property=properties.find(item=>item.id===charge.asset_id||String(item.code||'').toLowerCase()===String(charge.ref||'').toLowerCase());return <article key={charge.id} className="rounded border p-4"><div className="flex justify-between"><div><b>{charge.ref||'Bem sem código'} · {charge.client_name||'Cliente não informado'}</b><p className="text-xs">{companyNames.get(String(charge.company_id||''))||'Empresa não vinculada'} · {categoryNames.get(String(charge.category_id||''))||'Categoria não vinculada'} · {charge.status}</p></div><b>{brl(charge.value)}</b></div><div className="mt-3 flex flex-wrap gap-2"><PayChargeButton id={charge.id} disabled={charge.status==='pago'} onPaid={result=>{if(property)generateAgendaPropertyReceipt(charge,property,result.paidAt,String(result.transaction.id));setVersion(value=>value+1)}}/><ProtectedRecordActions table="charges" record={charge} fields={[{key:'client_name',label:'Cliente'},{key:'ref',label:'Código do bem'},{key:'due_date',label:'Vencimento',type:'date'},{key:'value',label:'Valor',type:'number'},{key:'status',label:'Status'},{key:'observation',label:'Observações'}]} onChanged={()=>setVersion(value=>value+1)}/></div>{property&&<p className="mt-2 text-[10px] text-secondary">Imóvel identificado: o recibo será baixado automaticamente após o pagamento.</p>}</article>})}</div></aside></>}
 </div>
}
function Card({label,value}:{label:string;value:string}){return <article className="rounded-xl border bg-white p-5"><small>{label}</small><b className="block text-xl">{value}</b></article>}
