import React, { useState } from 'react';
import { Pencil } from 'lucide-react';
import Modal from '../components/Modal';
import { getTrackerSummary, getTransactions, saveTrackerSummary } from '../mockData';
import { TrackerSummary } from '../types';

const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export default function Equipamentos() {
  const [version, setVersion] = useState(0); const [open, setOpen] = useState(false); const [error, setError] = useState('');
  const summary = getTrackerSummary(); const [form, setForm] = useState<TrackerSummary>(summary);
  const tx = getTransactions().filter(t => t.company === '3A RASTREAR'); const revenues = tx.filter(t => t.type === 'receita' && t.status === 'pago').reduce((s, t) => s + Math.abs(t.value), 0); const expenses = tx.filter(t => t.type === 'despesa' && t.status === 'pago').reduce((s, t) => s + Math.abs(t.value), 0);
  const save = (event: React.FormEvent) => { event.preventDefault(); setError(''); try { saveTrackerSummary({ ...form, updatedAt: new Date().toISOString() }); setOpen(false); setVersion(v => v + 1); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar.'); } };
  return <div className="space-y-6"><header className="flex justify-between gap-3"><div><h1 className="font-display text-xl font-black">3A RASTREAR — Financeiro Geral</h1><p className="text-xs text-secondary">Indicadores agregados, sem cadastro individual de rastreadores.</p></div><button onClick={() => { setForm(summary); setOpen(true); }} className="flex items-center gap-2 rounded bg-primary-container px-4 py-2 text-xs font-black"><Pencil className="w-4"/> ATUALIZAR INDICADOR</button></header><section className="grid gap-3 md:grid-cols-3"><Card label="Receitas" value={money(revenues)}/><Card label="Despesas" value={money(expenses)}/><Card label="Resultado líquido" value={money(revenues - expenses)}/></section><section className="grid gap-3 md:grid-cols-4"><Card label="Total de ativos" value={summary.total}/><Card label="Disponíveis" value={summary.available}/><Card label="Instalados" value={summary.installed}/><Card label="Em manutenção" value={summary.maintenance}/></section><p className="text-xs text-secondary">Última atualização: {summary.updatedAt ? new Date(summary.updatedAt).toLocaleString('pt-BR') : 'Não informado'}</p><section className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-xs"><thead className="bg-gray-50 text-left"><tr><th className="p-3">Data</th><th>Descrição</th><th>Categoria</th><th>Tipo</th><th>Status</th><th>Valor</th></tr></thead><tbody>{tx.map(t => <tr key={t.id} className="border-t"><td className="p-3">{t.date}</td><td>{t.description}</td><td>{t.category}</td><td>{t.type}</td><td>{t.status}</td><td>{money(t.value)}</td></tr>)}</tbody></table>{!tx.length && <p className="p-5 text-xs text-secondary">Nenhum lançamento financeiro cadastrado.</p>}</section><Modal isOpen={open} onClose={() => setOpen(false)} title="Indicador agregado 3A RASTREAR"><form onSubmit={save} className="grid grid-cols-2 gap-3">{([['total','Total de ativos'],['available','Disponíveis'],['installed','Instalados'],['maintenance','Em manutenção']] as const).map(([key,label]) => <label key={key} className="text-xs font-bold">{label}<input required min="0" type="number" value={form[key]} onChange={e => setForm({...form, [key]: Number(e.target.value)})} className="mt-1 w-full border p-2"/></label>)}{error && <p className="col-span-2 text-xs text-red-700">{error}</p>}<button className="col-span-2 bg-primary-container p-3 font-black">SALVAR INDICADOR</button></form></Modal></div>;
}
function Card({ label, value }: { label: string; value: React.ReactNode }) { return <article className="rounded-xl border bg-white p-5"><p className="text-[10px] font-bold uppercase text-secondary">{label}</p><b className="text-lg">{value}</b></article>; }
