import React,{useState}from'react';
import{Navigate,useNavigate}from'react-router-dom';
import{AuthenticationError,ProfileLoadError,useAuth}from'../auth/AuthContext';

export default function Login(){
  const{loading,session,profile,signIn,requestPasswordReset}=useAuth(),navigate=useNavigate();
  const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  if(!loading&&session&&profile)return <Navigate to="/" replace/>;
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(busy)return;setBusy(true);setMessage('');try{await signIn(email.trim(),password);navigate('/',{replace:true});}catch(error){if(error instanceof ProfileLoadError)setMessage(error.message);else if(error instanceof AuthenticationError)setMessage(`Falha na autenticação: ${error.message}`);else setMessage(error instanceof Error?error.message:'Não foi possível concluir o login.');}finally{setBusy(false);}};
  const recover=async()=>{if(busy)return;if(!email.trim()){setMessage('Informe seu e-mail primeiro.');return;}setBusy(true);setMessage('');try{await requestPasswordReset(email.trim());setMessage('Solicitação enviada pelo Supabase. Verifique seu e-mail.');}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível solicitar a recuperação.');}finally{setBusy(false);}};
  return <main className="min-h-screen bg-background grid place-items-center p-4"><section className="w-full max-w-sm rounded-2xl border bg-white p-7 shadow-xl"><img src={`${import.meta.env.BASE_URL}assets/logo-grupo-3a.png`} alt="GRUPO 3A ERP" className="mx-auto h-28 w-28 object-contain"/><h1 className="text-center font-display text-xl font-black">Acessar ERP</h1>{loading&&<p className="mt-4 text-center text-xs">Verificando sessão...</p>}<form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-xs font-bold">E-mail<input required disabled={busy} type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 w-full rounded border p-3"/></label><label className="block text-xs font-bold">Senha<input required disabled={busy} type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full rounded border p-3"/></label>{message&&<p className="rounded bg-gray-50 p-3 text-xs">{message}</p>}<button disabled={busy||loading} className="w-full rounded bg-primary-container p-3 font-black disabled:opacity-60">{busy?'AGUARDE...':'ENTRAR'}</button><button type="button" onClick={recover} disabled={busy} className="w-full text-xs font-bold text-primary disabled:opacity-60">Recuperar senha</button></form></section></main>;
}
