import{useState}from'react';
import{ArrowRightLeft,Download,Loader2,ShieldCheck}from'lucide-react';
import{CompanyFinancial,invokeMigration,MigrationDryRun}from'../services/migrationSync';
const number=(value:number)=>value.toLocaleString('pt-BR'),money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function MigrationSync(){
 const[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[report,setReport]=useState<MigrationDryRun|null>(null);
 const run=async(action:'test'|'analyze')=>{if(busy)return;setBusy(true);setMessage('');try{if(action==='test'){const result=await invokeMigration<{connection:{connected:boolean;serverSide:boolean};sourceTables:Record<string,string>}>('test');setMessage(result.connection.connected&&result.connection.serverSide?`Conexão segura confirmada. ${Object.keys(result.sourceTables).length} módulos localizados.`:'Conexão não confirmada.')}else{const result=await invokeMigration<MigrationDryRun>('analyze');setReport(result);setMessage('Dry-run concluído com zero gravações.')}}catch(error){setMessage(error instanceof Error?error.message:'Falha na operação.')}finally{setBusy(false)}};
 const download=()=>{if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),anchor=document.createElement('a');anchor.href=url;anchor.download=`migracao-dry-run-${report.operationId}.json`;anchor.click();URL.revokeObjectURL(url)};
 return <div className="space-y-6"><header><h1 className="flex items-center gap-2 font-display text-xl font-black"><ArrowRightLeft className="text-amber-500"/> Migração e Sincronização</h1><p className="text-xs text-secondary">Comparação segura entre o ERP antigo e o novo. Política new_only.</p></header>
  <section className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-xs text-emerald-800"><ShieldCheck className="mb-2"/><b>PRIMEIRA ETAPA — SOMENTE LEITURA</b><p>Nenhum registro será inserido, alterado ou excluído.</p></section>
  <div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>run('test')} className="rounded bg-black px-4 py-2 text-xs font-black text-white">TESTAR CONEXÃO</button><button disabled={busy} onClick={()=>run('analyze')} className="rounded bg-primary-container px-4 py-2 text-xs font-black">EXECUTAR DRY-RUN</button><button disabled title="Exige autorização owner em uma etapa separada" className="rounded border px-4 py-2 text-xs font-black opacity-40">IMPORTAR SOMENTE NOVOS</button>{report&&<button onClick={download} className="flex items-center gap-2 rounded border px-4 py-2 text-xs font-black"><Download className="w-4"/> BAIXAR RELATÓRIO</button>}</div>
  {busy&&<div className="flex items-center gap-2 text-sm"><Loader2 className="animate-spin"/> Processando todas as páginas...</div>}{message&&<p className="rounded border bg-white p-3 text-xs">{message}</p>}
  {report&&<><section className={`rounded border p-4 text-xs font-bold ${report.validation.matchesExpected?'border-emerald-300 bg-emerald-50 text-emerald-800':'border-amber-300 bg-amber-50 text-amber-800'}`}>Financeiro: {number(report.financial.transactions)} transações · {number(report.financial.revenues)} receitas · {number(report.financial.expenses)} despesas · {report.financial.firstDate||'—'} a {report.financial.lastDate||'—'}</section>
   <section className="grid gap-3 md:grid-cols-5">{[['Novos',report.summary.new],['Duplicados',report.summary.duplicates],['Conflitos',report.summary.conflicts],['Inválidos',report.summary.invalid],['Quarentena',report.summary.quarantine]].map(([label,value])=><article key={label} className="rounded-xl border bg-white p-4"><small>{label}</small><b className="block text-xl">{number(value as number)}</b></article>)}</section>
   <section className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-xs"><thead><tr><th className="p-3 text-left">Módulo</th><th>Antigo</th><th>Novo</th><th>Novos</th><th>Duplicados</th><th>Conflitos</th><th>Inválidos</th></tr></thead><tbody>{report.comparisons.map(row=><tr key={row.module} className="border-t text-center"><td className="p-3 text-left font-bold">{row.module}</td><td>{number(row.oldTotal)}</td><td>{number(row.currentTotal)}</td><td>{number(row.new)}</td><td>{number(row.duplicates)}</td><td>{number(row.conflicts)}</td><td>{number(row.invalid)}</td></tr>)}</tbody></table></section>
   <section className="rounded-xl border bg-white p-5"><h2 className="font-black">Totais por empresa</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{(Object.entries(report.financial.totalsByCompany)as Array<[string,CompanyFinancial]>).map(([company,row])=><article key={company} className="rounded border p-3 text-xs"><b>{company}</b><p>Total: {row.total} · Receitas: {row.revenues} ({money(row.revenueValue)})</p><p>Despesas: {row.expenses} ({money(row.expenseValue)})</p></article>)}</div></section>
   {!!report.quarantine.total&&<section className="rounded-xl border border-amber-200 bg-white p-5"><h2 className="font-black">Quarentena ({report.quarantine.total})</h2><ul className="mt-2 max-h-64 overflow-auto text-xs">{report.quarantine.items.map((item,index)=><li key={`${item.module}-${item.id}-${index}`} className="border-t py-2"><b>{item.module}</b> · {item.id||'sem UUID'} · {item.reason}</li>)}</ul>{report.quarantine.truncated&&<p className="text-xs">Lista resumida no navegador; o total permanece preservado.</p>}</section>}
   <p className="text-xs font-bold text-emerald-700">Zero gravações: antigo {report.zeroWrites.oldDatabase?'confirmado':'não'} · novo {report.zeroWrites.newDatabase?'confirmado':'não'} · importação real bloqueada</p></>}
 </div>;
}
