import pg from 'pg';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { extractLegacyZip } from '../src/services/legacyZipAdapter';
import { adaptLegacyBackup, diagnoseRoot } from '../src/services/legacyBackupAdapter';
import { inspectImport } from '../src/services/jsonImporter';
import { createRestorePlan } from '../src/services/restoreValidation';
import type { BackupAnalysis } from '../src/services/backupMaster';
import type { DataRepository, EntityRecord, RepositoryModule } from '../src/repositories/contracts';
const parse=(text:string)=>Object.fromEntries(text.split(/\r?\n/).map(line=>line.trim()).filter(line=>line&&!line.startsWith('#')&&line.includes('=')).map(line=>{const at=line.indexOf('=');return[line.slice(0,at),line.slice(at+1)]}));
const env={...parse(await readFile('.env.local','utf8')),...parse(await readFile('.env.supabase.local','utf8'))},projectRef=new URL(env.VITE_SUPABASE_URL).hostname.split('.')[0];
if(projectRef!=='eupfkkazjmprmaqdmlcm')throw new Error(`Projeto de destino não autorizado: ${projectRef}`);
const db=new pg.Client({host:`db.${projectRef}.supabase.co`,port:5432,database:'postgres',user:'postgres',password:env.SUPABASE_DB_PASSWORD,ssl:{rejectUnauthorized:false}}),zipPath='C:/Users/aandr/Downloads/backup_master_grupo3a_2026-07-19.zip';
await db.connect();
const modules:RepositoryModule[]=['companies','categories','clients','assets','properties','vehicles','bank_accounts','bank_movements','recurring_series','fixed_costs','charges','transactions','investments','alerts','receipts','company_metrics'];
const counts=async()=>Object.fromEntries(await Promise.all(modules.map(async module=>[module,Number((await db.query(`select count(*)::int count from public.${module}`)).rows[0].count)])));
let writes=0;const repository:DataRepository={kind:'localStorage',async list<T extends EntityRecord>(module:RepositoryModule){return(await db.query(`select * from public.${module}`)).rows as T[]},async find(){return null},async create(_module,record){writes++;return record},async update(_module,record){writes++;return record},async remove(){writes++},async runAtomically(_modules,operation){return operation()}};
try{
 const before=await counts();if(Object.entries(before).some(([module,count])=>module!=='companies'&&count!==0))throw new Error('Destino não está vazio; restauração automática bloqueada para evitar repetição.');
 const bytes=await readFile(zipPath),hash=createHash('sha256').update(bytes).digest('hex'),buffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)as ArrayBuffer,extracted=await extractLegacyZip(buffer),adapted=adaptLegacyBackup(extracted.root,diagnoseRoot(extracted.root,extracted.diagnostic.encoding));
 const analysis:BackupAnalysis={backup:null,convertedModules:adapted.modules,report:await inspectImport(repository,adapted.modules,true),diagnostic:extracted.diagnostic,adapterQuarantine:adapted.quarantine},plan=await createRestorePlan(repository,analysis,hash);
 if(!plan.ready||!plan.summary.consistent||plan.summary.criticalErrors)throw new Error('Plano real não está pronto ou consistente.');
 const owner=(await db.query("select id from public.profiles where role='owner' and active limit 1")).rows[0];if(!owner)throw new Error('Owner ativo não encontrado.');
 const payload=Object.fromEntries(Object.entries(plan.records).filter(([module])=>module!=='deletion_logs'));
 await db.query('begin');await db.query('set local role authenticated');await db.query("select set_config('request.jwt.claims',$1,true)",[JSON.stringify({sub:owner.id,role:'authenticated'})]);
 const call=await db.query("select public.restore_backup_new_only($1,$2,$3,$4::jsonb,false) result",[plan.operationId,plan.fileHash,plan.willInsert,JSON.stringify(payload)]),result=call.rows[0].result;
 if(result.status!=='completed'||result.inserted!==plan.willInsert){await db.query('rollback');throw new Error(result.error||`RPC retornou ${result.status}.`);}await db.query('commit');
 const after=await counts(),inserted=Object.fromEntries(modules.map(module=>[module,after[module]-before[module]]));
 console.log(JSON.stringify({projectRef,operationId:plan.operationId,status:result.status,plannedOperations:plan.willInsert,quarantine:plan.quarantine,insertedByModule:inserted,totalRowsAfter:after,realRestoreCompleted:true,writesOutsideRpc:writes},null,2));
}catch(error){await db.query('rollback').catch(()=>{});throw error}finally{await db.end()}
