import{createClient}from'@supabase/supabase-js';import pg from'pg';import{readFile,writeFile}from'node:fs/promises';
type Row={id?:string;[key:string]:unknown};const parse=(text:string)=>Object.fromEntries(text.split(/\r?\n/).map(x=>x.trim()).filter(x=>x&&!x.startsWith('#')&&x.includes('=')).map(x=>{const i=x.indexOf('=');return[x.slice(0,i),x.slice(i+1)]})),local={...parse(await readFile('.env.local','utf8')),...parse(await readFile('.env.supabase.local','utf8'))},source=await readFile('C:/Users/aandr/OneDrive/Área de Trabalho/SITES/GITHUB/grupo-3A-v27.12.2025-main/lib/supabase.ts','utf8'),oldUrl=source.match(/https:\/\/[a-z0-9]+\.supabase\.co/i)?.[0],oldKey=source.match(/sb_publishable_[A-Za-z0-9_-]+/)?.[0];if(!oldUrl||!oldKey)throw Error('Origem não configurada.');
const old=createClient(oldUrl,oldKey,{auth:{persistSession:false}}),ref=new URL(local.VITE_SUPABASE_URL).hostname.split('.')[0],db=new pg.Client({host:`db.${ref}.supabase.co`,port:5432,database:'postgres',user:'postgres',password:local.SUPABASE_DB_PASSWORD,ssl:{rejectUnauthorized:false}});await db.connect();let writes=0;
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,norm=(v:unknown)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),type=(v:unknown)=>['in','entrada','receita','credito'].includes(norm(v))?'receita':['out','saida','despesa','debito'].includes(norm(v))?'despesa':v;
async function pages(table:string){const c=await old.from(table).select('id',{head:true,count:'exact'});if(c.error)throw Error(`${table}: ${c.error.message}`);const rows:Row[]=[];for(let n=0;;n+=1000){let q=old.from(table).select('*');q=table==='transactions'?q.order('date').order('id'):q.order('id');const{data,error}=await q.range(n,n+999);if(error)throw Error(`${table}: ${error.message}`);if(!data?.length)break;rows.push(...data)}const unique=new Map(rows.map(r=>[String(r.id),r]));if(unique.size!==(c.count??0))throw Error(`${table}: contagem divergente`);return[...unique.values()]}
const oldCompanies=await pages('companies'),oldCategories=await pages('categories'),oldClients=await pages('clients'),oldProperties=await pages('properties'),oldVehicles=await pages('motorcycles'),oldCharges=await pages('charges'),oldFixed=await pages('fixed_costs'),oldTransactions=await pages('transactions'),oldAssets:Row[]=[...oldProperties.map(r=>({...r,asset_type:r.tipo??'imovel'})),...oldVehicles.map(r=>({...r,asset_type:r.type??'moto'}))],sources:Record<string,Row[]>={companies:oldCompanies,categories:oldCategories,clients:oldClients,assets:oldAssets,properties:oldProperties,vehicles:oldVehicles,charges:oldCharges,fixed_costs:oldFixed,transactions:oldTransactions};
const comparisons=[];let newTotal=0,duplicates=0,conflicts=0,quarantine=0;for(const[module,rows]of Object.entries(sources)){const current=(await db.query(`select * from public.${module}`)).rows as Row[],byId=new Map(current.map(r=>[String(r.id),r]));let fresh=0,dupes=0,different=0,invalid=0;for(const row of rows){const id=String(row.id??'');if(!uuid.test(id)||(module==='transactions'&&!row.company_id)){invalid++;continue}const existing=byId.get(id);if(!existing)fresh++;else{const sourceType=module==='transactions'?type(row.type):row.type,targetType=module==='transactions'?type(existing.type):existing.type;if(sourceType===targetType&&String(row.company_id??'')===String(existing.company_id??''))dupes++;else different++}}newTotal+=fresh;duplicates+=dupes;conflicts+=different;quarantine+=invalid;comparisons.push({module,old:rows.length,current:current.length,new:fresh,duplicates:dupes,conflicts:different,invalid})}
const dates=oldTransactions.map(r=>String(r.date??'')).filter(Boolean).sort(),companyNames=new Map(oldCompanies.map(r=>[String(r.id),String(r.name)])),financial:Record<string,{revenues:number;expenses:number;revenueValue:number;expenseValue:number}>={};for(const row of oldTransactions){const name=companyNames.get(String(row.company_id))??'Sem empresa comprovável',item=financial[name]??={revenues:0,expenses:0,revenueValue:0,expenseValue:0},value=Math.abs(Number(row.value)||0),kind=type(row.type);if(kind==='receita'){item.revenues++;item.revenueValue+=value}else if(kind==='despesa'){item.expenses++;item.expenseValue+=value}financial[name]=item}
const report={projectRef:ref,comparisons,firstDate:dates[0],lastDate:dates.at(-1),summary:{new:newTotal,duplicates,conflicts,quarantine},financial,writes};await writeFile('C:/Users/aandr/Downloads/migracao-sincronizacao-dry-run.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await db.end();
