import type{RentalGuarantee}from'../src/types';const storage=new Map<string,string>();Object.assign(globalThis,{localStorage:{getItem:(key:string)=>storage.get(key)??null,setItem:(key:string,value:string)=>storage.set(key,value),removeItem:(key:string)=>storage.delete(key)},window:{dispatchEvent:()=>true}});const data=await import('../src/mockData');
const accountA=crypto.randomUUID(),accountB=crypto.randomUUID(),clientId=crypto.randomUUID();data.saveBankAccounts([{id:accountA,bankName:'Banco A',accountName:'Conta A',type:'corrente',company:'IMÓVEIS',initialBalance:0,initialBalanceDate:'2026-07-21',active:true},{id:accountB,bankName:'Banco B',accountName:'Conta B',type:'corrente',company:'IMÓVEIS',initialBalance:0,initialBalanceDate:'2026-07-21',active:true}]);
const make=(assetId:string,guarantee:any)=>data.addCharge({dueDate:'2026-08-01',description:'Aluguel',company:'IMÓVEIS',client:'Cliente',value:1000,status:'pendente',category:'Aluguel',frequency:'mensal',recurrenceActive:true,clientId,assetId,assetCode:'01KIT',assetName:'Imóvel',assetType:'imovel',propertyId:assetId,rentalGuarantee:guarantee});
const withAccount:RentalGuarantee={id:crypto.randomUUID(),type:'cash_deposit',value:500,receivedAt:'2026-07-21',bankAccountId:accountA,status:'recebida',balance:500,history:[]},chargeA=make(crypto.randomUUID(),withAccount);data.saveRentalGuarantee(chargeA.id,withAccount);data.saveRentalGuarantee(chargeA.id,data.getCharges().find(item=>item.id===chargeA.id)!.rentalGuarantee!);
if(data.getBankMovements().filter(item=>item.guaranteeId===withAccount.id).length!==1||data.getTransactions().filter(item=>item.guaranteeId===withAccount.id).length!==1||data.getAccountBalance(accountA)!==500)throw new Error('Caução com conta falhou ou duplicou.');
const withoutAccount:RentalGuarantee={id:crypto.randomUUID(),type:'cash_deposit',value:300,receivedAt:'2026-07-21',status:'recebida',balance:300,history:[]},chargeB=make(crypto.randomUUID(),withoutAccount);data.saveRentalGuarantee(chargeB.id,withoutAccount);const txB=data.getTransactions().find(item=>item.guaranteeId===withoutAccount.id);if(!txB||txB.bankAccountId||data.getAccountBalance(accountB)!==0)throw new Error('Caução sem conta alterou banco.');data.linkGuaranteeTransactionToAccount(txB.id,accountB);data.linkGuaranteeTransactionToAccount(txB.id,accountB);if(data.getAccountBalance(accountB)!==300||data.getBankMovements().filter(item=>item.guaranteeId===withoutAccount.id).length!==1)throw new Error('Vínculo posterior duplicou saldo.');
const bond:RentalGuarantee={id:crypto.randomUUID(),type:'guarantor',value:1000,status:'pendente',balance:1000,history:[]},chargeC=make(crypto.randomUUID(),bond);data.saveRentalGuarantee(chargeC.id,bond);if(data.getTransactions().some(item=>item.guaranteeId===bond.id))throw new Error('Fiança sem recebimento criou lançamento.');
if(data.getTransactions().filter(item=>item.nature==='caucao_passivo').some(item=>item.type!=='receita'))throw new Error('Natureza inválida.');
console.log('GUARANTEE_OPTIONAL_ACCOUNT=OK WITH_ACCOUNT=OK WITHOUT_ACCOUNT=OK LATE_LINK=ONCE DUPLICATE=BLOCKED BOND_NO_RECEIPT=NO_MOVEMENT');
