import{createRestorePlan,executeRestorePlan,restoreAuthorizationValid,RestorePlan}from'../src/services/restoreValidation';
import{extractLegacyZip}from'../src/services/legacyZipAdapter';
import type{BackupAnalysis}from'../src/services/backupMaster';
import type{DataRepository,EntityRecord,RepositoryModule}from'../src/repositories/contracts';
class MemoryRepository implements DataRepository{readonly kind='localStorage' as const;data=new Map<RepositoryModule,EntityRecord[]>();failAfter=Infinity;writes=0;async list<T extends EntityRecord>(module:RepositoryModule){return[...(this.data.get(module)||[])]as T[]}async find<T extends EntityRecord>(module:RepositoryModule,id:string){return(await this.list<T>(module)).find(item=>item.id===id)||null}async create<T extends EntityRecord>(module:RepositoryModule,record:T){this.writes++;if(this.writes>this.failAfter)throw new Error('Falha simulada.');this.data.set(module,[record,...(this.data.get(module)||[])]);return record}async update<T extends EntityRecord>(_module:RepositoryModule,record:T){return record}async remove(){}async runAtomically<T>(_modules:RepositoryModule[],operation:()=>Promise<T>){const snapshot=new Map([...this.data].map(([key,value])=>[key,[...value]]));try{return await operation()}catch(error){this.data=snapshot;throw error}}}
const id1='11111111-1111-4111-8111-111111111111',id2='22222222-2222-4222-8222-222222222222';
const analysis=(records:EntityRecord[],invalid=false):BackupAnalysis=>({backup:null,convertedModules:{companies:records},diagnostic:{encoding:'UTF-8',rootType:'object',topLevelKeys:[],version:'test',metadataKeys:[],modulesFound:['companies'],encrypted:false,serialized:false,format:'legacy'},adapterQuarantine:[],report:{mode:'new_only',dryRun:true,valid:{companies:invalid?0:records.length},duplicates:{},conflicts:[],invalid:invalid?[{module:'companies',index:0,reason:'Campo obrigatório ausente.',record:{}}]:[],accepted:{companies:invalid?[]:records}}});
const repository=new MemoryRepository(),valid=await createRestorePlan(repository,analysis([{id:id1,name:'Empresa',kind:'holding'}]),'hash');if(!valid.ready)throw new Error('Arquivo válido bloqueado.');
const duplicate=await createRestorePlan(repository,analysis([{id:id1,name:'A',kind:'holding'},{id:id1,name:'B',kind:'holding'}]),'hash');if(!duplicate.ready||duplicate.summary.quarantine!==1||duplicate.summary.ready!==1)throw new Error('Erro individual não foi isolado na quarentena.');
const missing=await createRestorePlan(repository,analysis([{id:id1,name:'Empresa'}],true),'hash');if(missing.ready)throw new Error('Campo ausente aceito.');
const relationAnalysis=analysis([]);relationAnalysis.convertedModules={categories:[{id:id2,company_id:id1,name:'Categoria'}]};relationAnalysis.report.valid={categories:1};relationAnalysis.report.accepted={categories:[{id:id2,company_id:id1,name:'Categoria'}]};const relation=await createRestorePlan(repository,relationAnalysis,'hash');if(relation.ready)throw new Error('Relação inexistente aceita.');
let corrupted=false;try{await extractLegacyZip(new Uint8Array([1,2,3]).buffer)}catch{corrupted=true}if(!corrupted)throw new Error('ZIP corrompido aceito.');
const rollbackRepository=new MemoryRepository();rollbackRepository.failAfter=1;const rollbackPlan={...valid,operationId:crypto.randomUUID(),willInsert:2,records:{companies:[{id:id1,name:'A',kind:'holding'},{id:id2,name:'B',kind:'holding'}]}}as RestorePlan;let failed=false;try{await executeRestorePlan(rollbackRepository,rollbackPlan)}catch{failed=true}if(!failed||(await rollbackRepository.list('companies')).length!==0)throw new Error('Rollback falhou.');
if(valid.willInsert!==valid.summary.plannedOperations||valid.quarantine!==valid.summary.conflicts+valid.summary.invalid||valid.summary.total!==valid.summary.valid+valid.summary.duplicates+valid.summary.conflicts+valid.summary.invalid)throw new Error('Contagem canônica divergente.');
const tampered={...valid,willInsert:valid.willInsert+1}as RestorePlan;let divergenceBlocked=false;try{await executeRestorePlan(repository,tampered)}catch{divergenceBlocked=true}if(!divergenceBlocked)throw new Error('Plano divergente foi aceito.');
if(relation.ready||relation.summary.quarantine!==1||relation.summary.criticalErrors!==0)throw new Error('Relação inválida não foi isolada corretamente.');
if(restoreAuthorizationValid('operator',true,'RESTAURAR BACKUP')||restoreAuthorizationValid('owner',false,'RESTAURAR BACKUP')||restoreAuthorizationValid('owner',true,'frase errada'))throw new Error('Proteção owner falhou.');
console.log('RESTORE_VALIDATION=OK VALID=OK CORRUPTED=BLOCKED DUPLICATE=BLOCKED MISSING=BLOCKED RELATION=BLOCKED BATCH_FAILURE=ROLLED_BACK OPERATOR=BLOCKED WRONG_PASSWORD=BLOCKED WRITES_REMOTE=0');
