import pg from 'pg';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { extractLegacyZip } from '../src/services/legacyZipAdapter';
import { adaptLegacyBackup, diagnoseRoot } from '../src/services/legacyBackupAdapter';
import { inspectImport } from '../src/services/jsonImporter';
import { createRestorePlan } from '../src/services/restoreValidation';
import type { BackupAnalysis } from '../src/services/backupMaster';
import type { DataRepository, EntityRecord, RepositoryModule } from '../src/repositories/contracts';
const operationId='baf0f7c1-6386-4c67-b0b4-bff610e13fba',zipPath='C:/Users/aandr/Downloads/backup_master_grupo3a_2026-07-19.zip';
const parse=(text:string)=>Object.fromEntries(text.split(/\r?\n/).map(line=>line.trim()).filter(line=>line&&!line.startsWith('#')&&line.includes('=')).map(line=>{const at=line.indexOf('=');return[line.slice(0,at),line.slice(at+1)]}));
const env={...parse(await readFile('.env.local','utf8')),...parse(await readFile('.env.supabase.local','utf8'))},projectRef=new URL(env.VITE_SUPABASE_URL).hostname.split('.')[0];if(projectRef!=='eupfkkazjmprmaqdmlcm')throw new Error('Projeto de destino não autorizado.');
const db=new pg.Client({host:`db.${projectRef}.supabase.co`,port:5432,database:'postgres',user:'postgres',password:env.SUPABASE_DB_PASSWORD,ssl:{rejectUnauthorized:false}}),modules:RepositoryModule[]=['companies','categories','clients','assets','properties','vehicles','bank_accounts','bank_movements','transactions','charges','recurring_series','fixed_costs','investments','alerts','deletion_logs','receipts','company_metrics'];
await db.connect();const emptyRepository:DataRepository={kind:'localStorage',async list<T extends EntityRecord>(){return[]as T[]},async find(){return null},async create(_module,record){return record},async update(_module,record){return record},async remove(){},async runAtomically(_modules,operation){return operation()}};
try{
 const operation=(await db.query('select id,status,file_hash,expected_inserts,inserted_count from public.restore_operations where id=$1',[operationId])).rows[0];if(!operation||operation.status!=='completed')throw new Error('Operação concluída não encontrada.');
 const state:Record<string,unknown[]>={};for(const module of modules)state[module]=(await db.query(`select * from public.${module}`)).rows;const backup={format:'GRUPO_3A_PRE_ROLLBACK',createdAt:new Date().toISOString(),projectRef,restoreOperationId:operationId,modules:state},serialized=JSON.stringify(backup,null,2),backupHash=createHash('sha256').update(serialized).digest('hex'),backupPath=`C:/Users/aandr/Downloads/grupo-3a-antes-rollback-${operationId}.json`;await writeFile(backupPath,serialized);
 const bytes=await readFile(zipPath),buffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)as ArrayBuffer,extracted=await extractLegacyZip(buffer),adapted=adaptLegacyBackup(extracted.root,diagnoseRoot(extracted.root,extracted.diagnostic.encoding)),analysis:BackupAnalysis={backup:null,convertedModules:adapted.modules,report:await inspectImport(emptyRepository,adapted.modules,true),diagnostic:extracted.diagnostic,adapterQuarantine:adapted.quarantine},plan=await createRestorePlan(emptyRepository,analysis,createHash('sha256').update(bytes).digest('hex'));
 if(plan.willInsert!==operation.expected_inserts)throw new Error(`Plano reconstruído (${plan.willInsert}) diverge da operação (${operation.expected_inserts}).`);
 const deleteOrder:RepositoryModule[]=['receipts','alerts','investments','fixed_costs','bank_movements','transactions','charges','recurring_series','properties','vehicles','assets','clients','categories','bank_accounts','company_metrics'],removed:Record<string,number>={};
 await db.query('begin');await db.query("set local session_replication_role='replica'");for(const module of deleteOrder){const ids=(plan.records[module]||[]).map(record=>record.id);if(!ids.length){removed[module]=0;continue;}const result=await db.query(`delete from public.${module} where id=any($1::uuid[])`,[ids]);removed[module]=result.rowCount||0;}await db.query("set local session_replication_role='origin'");await db.query("update public.restore_operations set status='rolled_back',inserted_count=0,error_message=$2,finished_at=now() where id=$1",[operationId,JSON.stringify({reason:'ROLLBACK SOLICITADO PELO OWNER',removed})]);
 const core=(await db.query("select name,count(*)::int count from public.companies where name in ('LOC MOTTUS','3A RASTREAR','IMÓVEIS','HOLDING GRUPO 3A') group by name order by name")).rows,remaining:Record<string,number>={};for(const module of modules.filter(module=>!['companies','deletion_logs'].includes(module)))remaining[module]=Number((await db.query(`select count(*)::int count from public.${module}`)).rows[0].count);if(core.length!==4||Object.values(remaining).some(count=>count!==0)){await db.query('rollback');throw new Error('Validação pós-rollback divergente; transação revertida.');}await db.query('commit');
 console.log(JSON.stringify({projectRef,operationId,backupPath,backupSha256:backupHash,removed,coreCompanies:core.map(row=>row.name),remaining,status:'rolled_back'},null,2));
}catch(error){await db.query('rollback').catch(()=>{});throw error}finally{await db.end()}
