import pg from 'pg';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { extractLegacyZip } from '../src/services/legacyZipAdapter';
import { adaptLegacyBackup, diagnoseRoot } from '../src/services/legacyBackupAdapter';
const parse=(text:string)=>Object.fromEntries(text.split(/\r?\n/).map(line=>line.trim()).filter(line=>line&&!line.startsWith('#')&&line.includes('=')).map(line=>{const at=line.indexOf('=');return[line.slice(0,at),line.slice(at+1)]}));
const env={...parse(await readFile('.env.local','utf8')),...parse(await readFile('.env.supabase.local','utf8'))},ref=new URL(env.VITE_SUPABASE_URL).hostname.split('.')[0],db=new pg.Client({host:`db.${ref}.supabase.co`,port:5432,database:'postgres',user:'postgres',password:env.SUPABASE_DB_PASSWORD,ssl:{rejectUnauthorized:false}}),zipPath='C:/Users/aandr/Downloads/backup_master_grupo3a_2026-07-19.zip';
const allowed=['LOC MOTTUS','3A RASTREAR','IMÓVEIS','HOLDING GRUPO 3A']as const;
type Allowed=typeof allowed[number];
const companyName=(value:unknown):Allowed|undefined=>{const text=String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(/loc[\s_-]*mottus|mottus/.test(text))return'LOC MOTTUS';if(/rastrear|rastreamento/.test(text))return'3A RASTREAR';if(/imoveis|imovel/.test(text))return'IMÓVEIS';if(/holding|grupo[\s_-]*3a/.test(text))return'HOLDING GRUPO 3A';};
const mask=(id:string)=>`${id.slice(0,4)}…${id.slice(-4)}`;
await db.connect();try{
 const operation=(await db.query("select id,status,created_at,finished_at from public.restore_operations where status='completed' order by created_at desc limit 1")).rows[0];if(!operation)throw new Error('Operação concluída ausente.');
 const bytes=await readFile(zipPath),buffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)as ArrayBuffer,extracted=await extractLegacyZip(buffer),adapted=adaptLegacyBackup(extracted.root,diagnoseRoot(extracted.root,extracted.diagnostic.encoding));
 const sourceTransactions=(adapted.modules.transactions||[]).filter((record):record is Record<string,unknown>=>Boolean(record)&&typeof record==='object'&&typeof(record as Record<string,unknown>).id==='string'),sourceById=new Map(sourceTransactions.map(record=>[String(record.id),record]));
 const companies=(await db.query('select id,name from public.companies')).rows,companyById=new Map(companies.map(row=>[row.id,row.name as Allowed])),sourceCompanyById=new Map((adapted.modules.companies||[]).filter((record):record is Record<string,unknown>=>Boolean(record)&&typeof record==='object').map(record=>[String(record.id),companyName(record.name)||companyName(record.kind)]));
 const categories=new Map((await db.query('select id,company_id from public.categories')).rows.map(row=>[row.id,row.company_id])),assets=new Map((await db.query('select id,company_id from public.assets')).rows.map(row=>[row.id,row.company_id])),clients=new Map((await db.query('select id,company_id from public.clients')).rows.map(row=>[row.id,row.company_id]));
 const rows=(await db.query('select id,company_id,category_id,asset_id,client_id,type,value from public.transactions')).rows.filter(row=>sourceById.has(row.id));
 const counts:Record<string,number>=Object.fromEntries([...allowed.map(name=>[name,0]),['Sem comprovação',0],['Conflitos',0]]),items=[]as unknown[],financialTotal=rows.reduce((sum,row)=>sum+(row.type==='receita'?Number(row.value):-Number(row.value)),0);
 for(const row of rows){const source=sourceById.get(row.id)!,evidence=[]as Array<{source:string;company:Allowed}>;const original=sourceCompanyById.get(String(source.company_id));if(original)evidence.push({source:'company_id original',company:original});for(const key of ['company','empresa','unidade']){const found=companyName(source[key]);if(found)evidence.push({source:`${key} original`,company:found});}const categoryCompany=companyById.get(categories.get(row.category_id));if(categoryCompany)evidence.push({source:'categoria',company:categoryCompany});const assetCompany=companyById.get(assets.get(row.asset_id));if(assetCompany)evidence.push({source:'bem',company:assetCompany});const clientCompany=companyById.get(clients.get(row.client_id));if(clientCompany)evidence.push({source:'cliente',company:clientCompany});const unique=[...new Set(evidence.map(item=>item.company))],current=companyById.get(row.company_id),proposed=unique.length===1?unique[0]:undefined,status=unique.length>1?'Conflitos':proposed||'Sem comprovação';counts[status]=(counts[status]||0)+1;items.push({uuid:mask(row.id),current,proposed:proposed||null,evidence:evidence.map(item=>item.source),status});}
 const tables=['companies','categories','clients','assets','properties','vehicles','bank_accounts','bank_movements','transactions','charges','recurring_series','fixed_costs','investments','alerts','deletion_logs','receipts','company_metrics'],state:Record<string,unknown[]>={};for(const table of tables)state[table]=(await db.query(`select * from public.${table}`)).rows;
 const backup={format:'GRUPO_3A_PRE_COMPANY_CORRECTION',createdAt:new Date().toISOString(),projectRef:ref,restoreOperationId:operation.id,modules:state},serialized=JSON.stringify(backup,null,2),hash=createHash('sha256').update(serialized).digest('hex'),backupPath=`C:/Users/aandr/Downloads/grupo-3a-antes-correcao-empresas-${operation.id}.json`,reportPath=`C:/Users/aandr/Downloads/grupo-3a-dry-run-empresas-${operation.id}.json`;
 await writeFile(backupPath,serialized);await writeFile(reportPath,JSON.stringify({operation,scope:rows.length,counts,financialBefore:financialTotal,financialAfter:financialTotal,items,zeroUpdates:true},null,2));
 console.log(JSON.stringify({projectRef:ref,operationId:operation.id,scope:rows.length,counts,financialBefore:financialTotal,financialAfter:financialTotal,backupPath,backupSha256:hash,reportPath,zeroUpdates:true},null,2));
}finally{await db.end()}
